name: Create Plugin.jar

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Project
        uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven
      - name: Build and Package Plugin
        run: |
          artifactPath="$(pwd)/target"
          artifactName="$(mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout)"
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo "artifactPath=${artifactPath}" >> $GITHUB_ENV
          echo "artifactName=${artifactName}" >> $GITHUB_ENV
          echo git_hash=${git_hash} >> $GITHUB_ENV
          mvn clean package
          mv "${artifactPath}/${artifactName}.jar" "${artifactPath}/${artifactName}-${git_hash}.jar"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifactName }}-${{ env.git_hash }}.jar
          path: ${{ env.artifactPath }}/${{ env.artifactName }}-${{ env.git_hash }}.jar
      - name: Create Release (Only if tag push)
        uses: actions/create-release@v4
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
        with:
          tag_name: ${{ github.ref }}  # Use the pushed tag automatically
          release_name: "Snapshot ${{ github.sha }}"  # Informative release name
          body: |
            This release includes changes from commit ${{ github.sha }}.
          draft: false  # Create a published release by default
          prerelease: true
